"""Initial database schema

Revision ID: c7495cd14e3f
Revises: 
Create Date: 2025-11-20 15:13:44.781880+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7495cd14e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('direction_confidence', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('views', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_cameras', sa.Integer(), nullable=True),
    sa.Column('images_collected', sa.Integer(), nullable=True),
    sa.Column('images_analyzed', sa.Integer(), nullable=True),
    sa.Column('work_zones_detected', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_collection_id'), 'collection_runs', ['collection_id'], unique=True)
    op.create_index(op.f('ix_collection_runs_id'), 'collection_runs', ['id'], unique=False)
    op.create_index(op.f('ix_collection_runs_started_at'), 'collection_runs', ['started_at'], unique=False)
    op.create_table('camera_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('eastbound_heading', sa.Float(), nullable=True),
    sa.Column('westbound_heading', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('analysis_method', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'view_id', name='unique_camera_view_direction')
    )
    op.create_index(op.f('ix_camera_directions_camera_id'), 'camera_directions', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_directions_id'), 'camera_directions', ['id'], unique=False)
    op.create_table('work_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('workers', sa.Integer(), nullable=True),
    sa.Column('vehicles', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Integer(), nullable=True),
    sa.Column('barriers', sa.Boolean(), nullable=True),
    sa.Column('hazards', sa.JSON(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('mto_book_compliance', sa.Boolean(), nullable=True),
    sa.Column('gcp_image_url', sa.String(length=500), nullable=True),
    sa.Column('collection_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_zones_camera_id'), 'work_zones', ['camera_id'], unique=False)
    op.create_index(op.f('ix_work_zones_detected_at'), 'work_zones', ['detected_at'], unique=False)
    op.create_index(op.f('ix_work_zones_id'), 'work_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_zones_id'), table_name='work_zones')
    op.drop_index(op.f('ix_work_zones_detected_at'), table_name='work_zones')
    op.drop_index(op.f('ix_work_zones_camera_id'), table_name='work_zones')
    op.drop_table('work_zones')
    op.drop_index(op.f('ix_camera_directions_id'), table_name='camera_directions')
    op.drop_index(op.f('ix_camera_directions_camera_id'), table_name='camera_directions')
    op.drop_table('camera_directions')
    op.drop_index(op.f('ix_collection_runs_started_at'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_id'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_collection_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
